### ISSUE TITLE
Error converting file when using --images parameter (for stories under publications)

### ISSUE THREAD

**Issue by mmBs** [gautamdhameja/medium-2-md#18] opened 2020-10-18 21:53 UTC
Hi, first of all, thanks for this cool tool 👍 

When I try to convert with the command:

`medium-2-md convertLocal posts/ -i` this story: [Lucky 7 new tools and plugins for Android developers & designers](https://proandroiddev.com/lucky-7-new-tools-and-plugins-for-android-developers-designers-1545e5c59f27)

I got only 

`Error converting file: 2018-09-25_Lucky-7-new-tools-and-plugins-for-Android-developers---designers-1545e5c59f27.html. Skipping.`

What is interesting, my story [50 Android Studio Tips, Tricks & Resources you should be familiar with, as an Android Developer](https://medium.com/@mmbialas/50-android-studio-tips-tricks-resources-you-should-be-familiar-with-as-an-android-developer-af86e7cf56d2) is successfully converted with all images and gifs. 

`Completed: 2016-11-07_50-Android-Studio-Tips--Tricks---Resources-you-should-be-familiar-with--as-an-Android-Developer-af86e7cf56d2.md`

The only difference I noticed is that tips and tricks are not under any publication, however other stories are.

Please let me know where could be a problem.

Cheers 🍻

**Comment by bdfinst** [comment] 2020-11-28 11:49
I saw similar behavior and submitted a PR that may address it for you.

**Comment by mmBs** [comment] 2020-12-02 10:12
Hi @bdfinst. Thank you for the PR. I downloaded the last version from npm (https://www.npmjs.com/package/medium-2-md) but I get the same issue.
`Error converting file: 2018-09-25_Lucky-7-new-tools-and-plugins-for-Android-developers---designers-1545e5c59f27.html. Skipping.`

I also noticed, that all gifs / pngs are in temp folders, like `md_1606903525016`, so I believe this is somehow good behaviour.

**Comment by bdfinst** [comment] 2020-12-02 10:20
> Hi @bdfinst. Thank you for the PR. I downloaded the last version from npm (https://www.npmjs.com/package/medium-2-md) but I get the same issue.
> `Error converting file: 2018-09-25_Lucky-7-new-tools-and-plugins-for-Android-developers---designers-1545e5c59f27.html. Skipping.`
> 
> I also noticed, that all gifs / pngs are in temp folders, like `md_1606903525016`, so I believe this is somehow good behaviour.

The issue I fixed was related to metadata being in the wrong array position and causing an undefined property. This may help you track it down.
https://github.com/gautamdhameja/medium-2-md/pull/19/files

**Comment by epelaaez** [comment] 2021-04-16 16:20
I'm getting the same error where images are not being generated. Something interesting is that it works for one out of four posts I want to convert, all of which are published under a publication. I'm using the latest download, is there a solution yet for this problem? If so, what do I need to do?

**Comment by gautamdhameja** [comment] 2021-04-17 10:12
@epelaaez Can you point to which Medium post you are getting an error with? I'll test it out. Better, if you could just share the downloaded HTML file (Pastebin). I am unable to reproduce the error at my end with the data I have.

**Comment by epelaaez** [comment] 2021-04-17 13:45
Sure, I'll attach the three posts I'm having problems with here. The one that converts successfully is the Vectors and Scalars one, the other three show errors. 

[posts.zip](https://github.com/gautamdhameja/medium-2-md/files/6329343/posts.zip)

Thanks for your help.

**Comment by gautamdhameja** [comment] 2021-04-20 18:29
@epelaaez I was able to convert all the files that you shared just by using the latest version of the lib. Attaching below. Not sure what is causing the issue at your side. A couple of these files took a bit longer though.

[md_1618943195474.zip](https://github.com/gautamdhameja/medium-2-md/files/6345859/md_1618943195474.zip)

**Comment by epelaaez** [comment] 2021-04-20 18:34
Thanks, I will look into it.

**Comment by gautamdhameja** [comment] 2021-07-22 14:34
Closing as no repro.

**Closed as completed by gautamdhameja** 2021-07-22 14:34 UTC
